CREATE TABLE Pessoa(
	Id UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	Nome VARCHAR(90) NOT NULL,
	Nascimento DATETIME,
	Email VARCHAR(90),
	Tipo CHAR(1) NOT NULL,
	Usuario VARCHAR(30) NOT NULL,
	Senha VARCHAR(65)
)